trigger:
  batch: true
  branches:
    include:
      - '*'
pool:
  vmImage: 'ubuntu-latest'

variables:
  conftest_version: '0.18.2'

stages:
- stage: Build
  jobs:
  - job: Build_Task
    displayName: Build Task
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: './Tasks/ConftestInstaller'
    - script: |
        tsc
      displayName: Run Installer Task
      workingDirectory: ./Tasks/ConftestInstaller/
    - script: |
        node ./Tasks/ConftestInstaller/.bin/Index.js
      displayName: Run Installer Task
