trigger:
  batch: true
  branches:
    include:
      - '*'
pool:
  vmImage: 'ubuntu-latest'

variables:
  conftest_version: '0.18.2'

stages:
- stage: Build
  jobs:
  - job: Build_Task
    displayName: Build Task
    steps:
    - task: NodeTool@0 
      inputs:
        versionSpec: $(node_version)
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: './Tasks/ConftestInstaller'
      displayName: NPM Install ConftestInstaller
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: './Tasks/Conftest'
      displayName: NPM Install Conftest
    - script: |
        tsc
      displayName: Build ConftestInstaller Task
      workingDirectory: ./Tasks/ConftestInstaller/
    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: './Tasks/ConftestInstaller'
        customCommand: 'install mocha -g'
    - script: |
        mocha .bin/tests/_suite.js
      displayName: Unit Tests ConftestInstaller Task
      workingDirectory: ./Tasks/ConftestInstaller/
    - script: |
        export INPUT_CONFTESTVERSION="0.18.2"
        node ./Tasks/ConftestInstaller/.bin/Index.js
      displayName: Run ConftestInstaller Task
    - script: |
        tsc
      displayName: Build Conftest Task
      workingDirectory: ./Tasks/Conftest/
    - script: |
        export INPUT_CONFTESTCOMMAND="--version"
        export INPUT_CONFTESTARGS=""
        node ./Tasks/Conftest/.bin/Index.js
      displayName: Run Conftest Task Version
    - script: |
        export INPUT_CONFTESTCOMMAND="test"
        export INPUT_CONFTESTFILE="./tests/test.json"
        export INPUT_CONFTESTARGS=""
        node ./Tasks/Conftest/.bin/Index.js
      displayName: Run Conftest Task Test